volumes:
  blog_db: {}
  blog_db_backups: {}

services:
  db:
    build:
      context: .
      dockerfile: ./compose/db/Dockerfile
    image: blog_db
    volumes:
      - blog_db:/var/lib/postgresql/data
      - blog_db_backups:/backups
    env_file:
      - ./rust-blog/.env
    ports:
      - "5432:5432"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  app:
    build:
      context: .
      dockerfile: ./compose/app/Dockerfile
    image: blog_app
    depends_on:
      - db
    env_file:
      - ./rust-blog/.env
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: always
        delay: 5s