version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/usr/src
      - /usr/src/node_modules #Para que no se sobre escriba esta parte con el montado de arriba
    command: npx nodemon index.js

  db:
    image: mongo
